export const CHANNELS = {
  check_task: "check_task",
  get_accounts: "get_accounts",
  get_domains: "get_domains",
  get_metadatas: "get_metadatas",
  get_records: "get_records",
  delete_account: "delete_account",
  delete_domains: "delete_domains",
  delete_metadatas: "delete_metadatas",
  delete_records: "delete_records",
  update_account: "update_account",
  update_metadata: "update_metadata",
  update_domain: "update_domain",
  update_record: "update_record:",
  demine_task: "demine_task",
  login_task: "login_task",
  create_task: "create_task",
  confirm_task: "confirm_task",
  scrape_task: "scrape_task",
  add_domain: "add_domain", 
  add_account: "add_account",
  verify_domain: "verify_domain", 
  delete_domain: "delete_domain",
  register_domain: "register_domain",
  accounts_in_use: "accounts_in_use",
  filter_records: "filter_records"
}