export const proxyMockData = [
  { id: '1', protocol: 'https://000.000.000.000:8000', host: '000.000.000.000', port: '8000' },
  { id: '1', protocol: 'https://000.000.000.000:8000', host: '000.000.000.000', port: '8000' },
  { id: '1', protocol: 'https://000.000.000.000:8000', host: '000.000.000.000', port: '8000' },
  { id: '1', protocol: 'https://000.000.000.000:8000', host: '000.000.000.000', port: '8000' },
  { id: '1', protocol: 'https://000.000.000.000:8000', host: '000.000.000.000', port: '8000' },
  { id: '1', protocol: 'https://000.000.000.000:8000', host: '000.000.000.000', port: '8000' },
  { id: '1', protocol: 'https://000.000.000.000:8000', host: '000.000.000.000', port: '8000' },
  { id: '1', protocol: 'https://000.000.000.000:8000', host: '000.000.000.000', port: '8000' },
  { id: '1', protocol: 'https://000.000.000.000:8000', host: '000.000.000.000', port: '8000' },
  { id: '1', protocol: 'https://000.000.000.000:8000', host: '000.000.000.000', port: '8000' },
  { id: '1', protocol: 'https://000.000.000.000:8000', host: '000.000.000.000', port: '8000' },
  { id: '1', protocol: 'https://000.000.000.000:8000', host: '000.000.000.000', port: '8000' },
  { id: '1', protocol: 'https://000.000.000.000:8000', host: '000.000.000.000', port: '8000' },
  { id: '1', protocol: 'https://000.000.000.000:8000', host: '000.000.000.000', port: '8000' },
  { id: '1', protocol: 'https://000.000.000.000:8000', host: '000.000.000.000', port: '8000' },
  { id: '1', protocol: 'https://000.000.000.000:8000', host: '000.000.000.000', port: '8000' },
  { id: '1', protocol: 'https://000.000.000.000:8000', host: '000.000.000.000', port: '8000' },
  { id: '1', protocol: 'https://000.000.000.000:8000', host: '000.000.000.000', port: '8000' },
  { id: '1', protocol: 'https://000.000.000.000:8000', host: '000.000.000.000', port: '8000' },
  { id: '1', protocol: 'https://000.000.000.000:8000', host: '000.000.000.000', port: '8000' },
  { id: '1', protocol: 'https://000.000.000.000:8000', host: '000.000.000.000', port: '8000' },
  { id: '1', protocol: 'https://000.000.000.000:8000', host: '000.000.000.000', port: '8000' },
  { id: '1', protocol: 'https://000.000.000.000:8000', host: '000.000.000.000', port: '8000' },
  { id: '1', protocol: 'https://000.000.000.000:8000', host: '000.000.000.000', port: '8000' },
  { id: '1', protocol: 'https://000.000.000.000:8000', host: '000.000.000.000', port: '8000' },
  { id: '1', protocol: 'https://000.000.000.000:8000', host: '000.000.000.000', port: '8000' },
  { id: '1', protocol: 'https://000.000.000.000:8000', host: '000.000.000.000', port: '8000' },
  { id: '1', protocol: 'https://000.000.000.000:8000', host: '000.000.000.000', port: '8000' },
  { id: '1', protocol: 'https://000.000.000.000:8000', host: '000.000.000.000', port: '8000' },
  { id: '1', protocol: 'https://000.000.000.000:8000', host: '000.000.000.000', port: '8000' },
  { id: '1', protocol: 'https://000.000.000.000:8000', host: '000.000.000.000', port: '8000' },
  { id: '1', protocol: 'https://000.000.000.000:8000', host: '000.000.000.000', port: '8000' },
  { id: '1', protocol: 'https://000.000.000.000:8000', host: '000.000.000.000', port: '8000' },
  { id: '1', protocol: 'https://000.000.000.000:8000', host: '000.000.000.000', port: '8000' },
  { id: '1', protocol: 'https://000.000.000.000:8000', host: '000.000.000.000', port: '8000' }
]

export const accountMockData = [
  {
    id: '12345',
    domain: 'domain',
    recoveryEmail: '',

    accountType: 'free',
    trialTime: `${new Date('') || 'n/a'}`,
    isSuspended: false,
    email: 'msefdsadsadefsdfsdfssadswdaedasdsasada@h.co.uk',
    password: 'pass',
    cookies: 'dasdasdas',
    proxy: 'dsaasd',
    lastUsed: new Date()
  },
  {
    id: '54321',
    domain: 'domain2',
    recoveryEmail: '',

    accountType: 'prem',
    trialTime: new Date(),
    isSuspended: false,
    email: 'ms22@h.co.uk',
    password: 'pass2',
    cookies: 'dasdasdas22',
    proxy: 'dsaasd222',
    lastUsed: new Date()
  },
  {
    id: '12345',
    domain: 'domain',
    recoveryEmail: '',

    accountType: 'free',
    trialTime: new Date(),
    isSuspended: false,
    email: 'ms@h.co.uk',
    password: 'pass',
    cookies: 'dasdasdas',
    proxy: 'dsaasd',
    lastUsed: new Date()
  },
  {
    id: '54321',
    domain: 'domain2',
    recoveryEmail: '',

    accountType: 'prem',
    trialTime: new Date(),
    isSuspended: false,
    email: 'ms22@h.co.uk',
    password: 'pass2',
    cookies: 'dasdasdas22',
    proxy: 'dsaasd222',
    lastUsed: new Date()
  }
]

export const metaMockData = [
  {
    id: '12345',
    url: 'www.gom',
    params: { lol: 'fds', poll: 'cascas' },
    fullURL: 'dsadsa',
    name: 'dad',
    maxPages: 5,
    page: 1,
    scrapes: [{ page: 1, scrapeID: 'd' }]
  },
  {
    id: '12345',
    url: 'www.gom',
    params: { lol: 'cvxxc', poll: 'nhg' },
    fullURL: 'dsadsa',
    name: 'dad',
    maxPages: 5,
    page: 1,
    scrapes: [{ page: 2, scrapeID: 'd' }]
  },
  {
    id: '12345',
    url: 'www.gom',
    params: { lol: 'cxzc', poll: 'cascas' },
    fullURL: 'dsadsa',
    name: 'dad',
    maxPages: 5,
    page: 1,
    scrapes: [{ page: 3, scrapeID: 'd' }]
  },
  {
    id: '12345',
    url: 'www.gom',
    params: { lol: 'scxz', poll: 'ghf' },
    fullURL: 'dsadsa',
    name: 'dad',
    maxPages: 5,
    page: 1,
    scrapes: [{ page: 4, scrapeID: 'd' }]
  },
  {
    id: '12345',
    url: 'www.gom',
    params: { lol: 'dasdsad', poll: 'cascas' },
    fullURL: 'dsadsa',
    name: 'dad',
    maxPages: 5,
    page: 1,
    scrapes: [{ page: 5, scrapeID: 'd' }]
  },
  {
    id: '12345',
    url: 'www.gom',
    params: { lol: 'dscsc', poll: 'vcfg' },
    fullURL: 'dsadsa',
    name: 'dad',
    maxPages: 5,
    page: 1,
    scrapes: [{ page: 1, scrapeID: 'p' }]
  },
  {
    id: '12345',
    url: 'www.gom',
    params: { lol: 'dsada', poll: 'cascas' },
    fullURL: 'dsadsa',
    name: 'dad',
    maxPages: 5,
    page: 1,
    scrapes: [{ page: 2, scrapeID: 'p' }]
  },
  {
    id: '12345',
    url: 'www.gom',
    params: { lol: 'dasdsad', poll: 'ythgf' },
    fullURL: 'dsadsa',
    name: 'dad',
    maxPages: 5,
    page: 1,
    scrapes: [{ page: 3, scrapeID: 'p' }]
  },
  {
    id: '12345',
    url: 'www.gom',
    params: { lol: 'dsadas', poll: 'jmhg' },
    fullURL: 'dsadsa',
    name: 'dad',
    maxPages: 5,
    page: 1,
    scrapes: [{ page: 4, scrapeID: 'p' }]
  },
  {
    id: '12345',
    url: 'www.gom',
    params: { lol: 'cxzcxz', poll: 'cascas' },
    fullURL: 'dsadsa',
    name: 'dad',
    maxPages: 5,
    page: 1,
    scrapes: [{ page: 5, scrapeID: 'p' }]
  },
  {
    id: '12345',
    url: 'www.gom',
    params: { lol: 'dasdsad', poll: 'xcvdf' },
    fullURL: 'dsadsa',
    name: 'dad',
    maxPages: 4,
    page: 1,
    scrapes: [{ page: 1, scrapeID: 'c' }]
  },
  {
    id: '12345',
    url: 'www.gom',
    params: { lol: 'vsdsc', poll: 'dsvf' },
    fullURL: 'dsadsa',
    name: 'dad',
    maxPages: 4,
    page: 1,
    scrapes: [{ page: 2, scrapeID: 'c' }]
  },
  {
    id: '12345',
    url: 'www.gom',
    params: { lol: 'dasdsad', poll: 'vcxfr' },
    fullURL: 'dsadsa',
    name: 'dad',
    maxPages: 4,
    page: 1,
    scrapes: [{ page: 3, scrapeID: 'c' }]
  },
  {
    id: '12345',
    url: 'www.gom',
    params: { lol: 'hnfgbd', poll: 'kuyh' },
    fullURL: 'dsadsa',
    name: 'dad',
    maxPages: 4,
    page: 1,
    scrapes: [{ page: 4, scrapeID: 'c' }]
  },
  {
    id: '12345',
    url: 'www.gom',
    params: { lol: 'jmthgfd', poll: 'hntg' },
    fullURL: 'dsadsa',
    name: 'dad',
    maxPages: 1,
    page: 1,
    scrapes: [{ page: 1, scrapeID: 'e' }]
  },
  {
    id: '12345',
    url: 'www.gom',
    params: { lol: 'dasdsad', poll: 'cascas' },
    fullURL: 'dsadsa',
    name: 'dad',
    maxPages: 1,
    page: 1,
    scrapes: [{ page: 1, scrapeID: 'r' }]
  },
  {
    id: '12345',
    url: 'www.gom',
    params: { lol: 'hyrtfg', poll: 'fdre' },
    fullURL: 'dsadsa',
    name: 'dad',
    maxPages: 1,
    page: 1,
    scrapes: [{ page: 1, scrapeID: 't' }]
  },
  {
    id: '12345',
    url: 'www.gom',
    params: { lol: 'vfd', poll: 'dfer' },
    fullURL: 'dsadsa',
    name: 'dad',
    maxPages: 1,
    page: 1,
    scrapes: [{ page: 1, scrapeID: 'y' }]
  }
]

export const recordMockData = [
  {
    id: '12345',
    scrapeID: 'd',
    url: 'http:/dsadsa.com',
    page: 1,
    data: {
      Name: 'mike',
      Linkedin: 'fsd',
      Title: 'fdsfds',
      'Company Name': 'fdsjhbknlmjhjgvhjbknhjghjkbnhbjgkw',
      'Company Website': 'dsfw',
      'Company Linkedin': 'thre',
      'Company Twitter': 'grev',
      'Company Facebook': 'tgerf',
      Email: 'dfsfew',
      isVerified: true,
      Location: 'cvfgd',
      Employees: '8',
      Phone: '324532',
      Industry: 'fsdgre',
      Keywords: ['fdssf', 'fdse']
    }
  },
  {
    id: '54343',
    scrapeID: 'd',
    url: 'http:/dsadsa.com',
    page: 1,
    data: {
      Name: 'mike',
      Linkedin: 'fsd',
      Title: 'fdsfds',
      'Company Name': 'fdsw',
      'Company Website': 'dsfw',
      'Company Linkedin': 'thre',
      'Company Twitter': 'grev',
      'Company Facebook': 'tgerf',
      Email: 'dfsfew',
      isVerified: true,
      Location: 'cvfgd',
      Employees: '8',
      Phone: '324532',
      Industry: 'fsdgre',
      Keywords: ['fdssf', 'fdse']
    }
  },
  {
    id: '64536',
    scrapeID: 'd',
    url: 'http:/dsadsa.com',
    page: 1,
    data: {
      Name: 'mike',
      Linkedin: 'fsd',
      Title: 'fdsfds',
      'Company Name': 'fdsw',
      'Company Website': 'dsfw',
      'Company Linkedin': 'thre',
      'Company Twitter': 'grev',
      'Company Facebook': 'tgerf',
      Email: 'dfsfew',
      isVerified: true,
      Location: 'cvfgd',
      Employees: '8',
      Phone: '324532',
      Industry: 'fsdgre',
      Keywords: ['fdssf', 'fdse']
    }
  },
  {
    id: '64522',
    scrapeID: 'd',
    url: 'http:/dsadsa.com',
    page: 1,
    data: {
      Name: 'mike',
      Linkedin: 'fsd',
      Title: 'fdsfds',
      'Company Name': 'fdsw',
      'Company Website': 'dsfw',
      'Company Linkedin': 'thre',
      'Company Twitter': 'grev',
      'Company Facebook': 'tgerf',
      Email: 'dfsfew',
      isVerified: true,
      Location: 'cvfgd',
      Employees: '8',
      Phone: '324532',
      Industry: 'fsdgre',
      Keywords: ['fdssf', 'fdse']
    }
  },
  {
    id: '47657',
    scrapeID: 'd',
    url: 'http:/dsadsa.com',
    page: 1,
    data: {
      Name: 'mike',
      Linkedin: 'fsd',
      Title: 'fdsfds',
      'Company Name': 'fdsw',
      'Company Website': 'dsfw',
      'Company Linkedin': 'thre',
      'Company Twitter': 'grev',
      'Company Facebook': 'tgerf',
      Email: 'dfsfew',
      isVerified: true,
      Location: 'cvfgd',
      Employees: '8',
      Phone: '324532',
      Industry: 'fsdgre',
      Keywords: ['fdssf', 'fdse']
    }
  },
  {
    id: '83756',
    scrapeID: 'd',
    url: 'http:/dsadsa.com',
    page: 1,
    data: {
      Name: 'mike',
      Linkedin: 'fsd',
      Title: 'fdsfds',
      'Company Name': 'fdsw',
      'Company Website': 'dsfw',
      'Company Linkedin': 'thre',
      'Company Twitter': 'grev',
      'Company Facebook': 'tgerf',
      Email: 'dfsfew',
      isVerified: true,
      Location: 'cvfgd',
      Employees: '8',
      Phone: '324532',
      Industry: 'fsdgre',
      Keywords: ['fdssf', 'fdse']
    }
  },
  {
    id: '59878',
    scrapeID: 'd',
    url: 'http:/dsadsa.com',
    page: 1,
    data: {
      Name: 'mike',
      Linkedin: 'fsd',
      Title: 'fdsfds',
      'Company Name': 'fdsw',
      'Company Website': 'dsfw',
      'Company Linkedin': 'thre',
      'Company Twitter': 'grev',
      'Company Facebook': 'tgerf',
      Email: 'dfsfew',
      isVerified: true,
      Location: 'cvfgd',
      Employees: '8',
      Phone: '324532',
      Industry: 'fsdgre',
      Keywords: ['fdssf', 'fdse']
    }
  },
  {
    id: '34525',
    scrapeID: 'p',
    url: 'http:/dsadsa.com',
    page: 1,
    data: {
      Name: 'mike',
      Linkedin: 'fsd',
      Title: 'fdsfds',
      'Company Name': 'fdsw',
      'Company Website': 'dsfw',
      'Company Linkedin': 'thre',
      'Company Twitter': 'grev',
      'Company Facebook': 'tgerf',
      Email: 'dfsfew',
      isVerified: true,
      Location: 'cvfgd',
      Employees: '8',
      Phone: '324532',
      Industry: 'fsdgre',
      Keywords: ['fdssf', 'fdse']
    }
  },
  {
    id: '06890',
    scrapeID: 'p',
    url: 'http:/dsadsa.com',
    page: 1,
    data: {
      Name: 'mike',
      Linkedin: 'fsd',
      Title: 'fdsfds',
      'Company Name': 'fdsw',
      'Company Website': 'dsfw',
      'Company Linkedin': 'thre',
      'Company Twitter': 'grev',
      'Company Facebook': 'tgerf',
      Email: 'dfsfew',
      isVerified: true,
      Location: 'cvfgd',
      Employees: '8',
      Phone: '324532',
      Industry: 'fsdgre',
      Keywords: ['fdssf', 'fdse']
    }
  },
  {
    id: '24565',
    scrapeID: 'p',
    url: 'http:/dsadsa.com',
    page: 1,
    data: {
      Name: 'mike',
      Linkedin: 'fsd',
      Title: 'fdsfds',
      'Company Name': 'fdsw',
      'Company Website': 'dsfw',
      'Company Linkedin': 'thre',
      'Company Twitter': 'grev',
      'Company Facebook': 'tgerf',
      Email: 'dfsfew',
      isVerified: true,
      Location: 'cvfgd',
      Employees: '8',
      Phone: '324532',
      Industry: 'fsdgre',
      Keywords: ['fdssf', 'fdse']
    }
  },
  {
    id: '25464',
    scrapeID: 'p',
    url: 'http:/dsadsa.com',
    page: 1,
    data: {
      Name: 'mike',
      Linkedin: 'fsd',
      Title: 'fdsfds',
      'Company Name': 'fdsw',
      'Company Website': 'dsfw',
      'Company Linkedin': 'thre',
      'Company Twitter': 'grev',
      'Company Facebook': 'tgerf',
      Email: 'dfsfew',
      isVerified: true,
      Location: 'cvfgd',
      Employees: '8',
      Phone: '324532',
      Industry: 'fsdgre',
      Keywords: ['fdssf', 'fdse']
    }
  },
  {
    id: '65434',
    scrapeID: 'p',
    url: 'http:/dsadsa.com',
    page: 1,
    data: {
      Name: 'mike',
      Linkedin: 'fsd',
      Title: 'fdsfds',
      'Company Name': 'fdsw',
      'Company Website': 'dsfw',
      'Company Linkedin': 'thre',
      'Company Twitter': 'grev',
      'Company Facebook': 'tgerf',
      Email: 'dfsfew',
      isVerified: true,
      Location: 'cvfgd',
      Employees: '8',
      Phone: '324532',
      Industry: 'fsdgre',
      Keywords: ['fdssf', 'fdse']
    }
  },
  {
    id: '89758',
    scrapeID: 'c',
    url: 'http:/dsadsa.com',
    page: 1,
    data: {
      Name: 'mike',
      Linkedin: 'fsd',
      Title: 'fdsfds',
      'Company Name': 'fdsw',
      'Company Website': 'dsfw',
      'Company Linkedin': 'thre',
      'Company Twitter': 'grev',
      'Company Facebook': 'tgerf',
      Email: 'dfsfew',
      isVerified: true,
      Location: 'cvfgd',
      Employees: '8',
      Phone: '324532',
      Industry: 'fsdgre',
      Keywords: ['fdssf', 'fdse']
    }
  },
  {
    id: '35445',
    scrapeID: 'c',
    url: 'http:/dsadsa.com',
    page: 1,
    data: {
      Name: 'mike',
      Linkedin: 'fsd',
      Title: 'fdsfds',
      'Company Name': 'fdsw',
      'Company Website': 'dsfw',
      'Company Linkedin': 'thre',
      'Company Twitter': 'grev',
      'Company Facebook': 'tgerf',
      Email: 'dfsfew',
      isVerified: true,
      Location: 'cvfgd',
      Employees: '8',
      Phone: '324532',
      Industry: 'fsdgre',
      Keywords: ['fdssf', 'fdse']
    }
  },
  {
    id: '65423',
    scrapeID: 'c',
    url: 'http:/dsadsa.com',
    page: 1,
    data: {
      Name: 'mike',
      Linkedin: 'fsd',
      Title: 'fdsfds',
      'Company Name': 'fdsw',
      'Company Website': 'dsfw',
      'Company Linkedin': 'thre',
      'Company Twitter': 'grev',
      'Company Facebook': 'tgerf',
      Email: 'dfsfew',
      isVerified: true,
      Location: 'cvfgd',
      Employees: '8',
      Phone: '324532',
      Industry: 'fsdgre',
      Keywords: ['fdssf', 'fdse']
    }
  },
  {
    id: '45237',
    scrapeID: 'c',
    url: 'http:/dsadsa.com',
    page: 1,
    data: {
      Name: 'mike',
      Linkedin: 'fsd',
      Title: 'fdsfds',
      'Company Name': 'fdsw',
      'Company Website': 'dsfw',
      'Company Linkedin': 'thre',
      'Company Twitter': 'grev',
      'Company Facebook': 'tgerf',
      Email: 'dfsfew',
      isVerified: true,
      Location: 'cvfgd',
      Employees: '8',
      Phone: '324532',
      Industry: 'fsdgre',
      Keywords: ['fdssf', 'fdse']
    }
  },
  {
    id: '98677',
    scrapeID: 'e',
    url: 'http:/dsadsa.com',
    page: 1,
    data: {
      Name: 'mike',
      Linkedin: 'fsd',
      Title: 'fdsfds',
      'Company Name': 'fdsw',
      'Company Website': 'dsfw',
      'Company Linkedin': 'thre',
      'Company Twitter': 'grev',
      'Company Facebook': 'tgerf',
      Email: 'dfsfew',
      isVerified: true,
      Location: 'cvfgd',
      Employees: '8',
      Phone: '324532',
      Industry: 'fsdgre',
      Keywords: ['fdssf', 'fdse']
    }
  },
  {
    id: '09780',
    scrapeID: 'e',
    url: 'http:/dsadsa.com',
    page: 1,
    data: {
      Name: 'mike',
      Linkedin: 'fsd',
      Title: 'fdsfds',
      'Company Name': 'fdsw',
      'Company Website': 'dsfw',
      'Company Linkedin': 'thre',
      'Company Twitter': 'grev',
      'Company Facebook': 'tgerf',
      Email: 'dfsfew',
      isVerified: true,
      Location: 'cvfgd',
      Employees: '8',
      Phone: '324532',
      Industry: 'fsdgre',
      Keywords: ['fdssf', 'fdse']
    }
  },
  {
    id: '12346',
    scrapeID: 'e',
    url: 'http:/dsadsa.com',
    page: 1,
    data: {
      Name: 'mike',
      Linkedin: 'fsd',
      Title: 'fdsfds',
      'Company Name': 'fdsw',
      'Company Website': 'dsfw',
      'Company Linkedin': 'thre',
      'Company Twitter': 'grev',
      'Company Facebook': 'tgerf',
      Email: 'dfsfew',
      isVerified: true,
      Location: 'cvfgd',
      Employees: '8',
      Phone: '324532',
      Industry: 'fsdgre',
      Keywords: ['fdssf', 'fdse']
    }
  },
  {
    id: '56465',
    scrapeID: 'r',
    url: 'http:/dsadsa.com',
    page: 1,
    data: {
      Name: 'mike',
      Linkedin: 'fsd',
      Title: 'fdsfds',
      'Company Name': 'fdsw',
      'Company Website': 'dsfw',
      'Company Linkedin': 'thre',
      'Company Twitter': 'grev',
      'Company Facebook': 'tgerf',
      Email: 'dfsfew',
      isVerified: true,
      Location: 'cvfgd',
      Employees: '8',
      Phone: '324532',
      Industry: 'fsdgre',
      Keywords: ['fdssf', 'fdse']
    }
  },
  {
    id: '18735',
    scrapeID: 'r',
    url: 'http:/dsadsa.com',
    page: 1,
    data: {
      Name: 'mike',
      Linkedin: 'fsd',
      Title: 'fdsfds',
      'Company Name': 'fdsw',
      'Company Website': 'dsfw',
      'Company Linkedin': 'thre',
      'Company Twitter': 'grev',
      'Company Facebook': 'tgerf',
      Email: 'dfsfew',
      isVerified: true,
      Location: 'cvfgd',
      Employees: '8',
      Phone: '324532',
      Industry: 'fsdgre',
      Keywords: ['fdssf', 'fdse']
    }
  },
  {
    id: '65445',
    scrapeID: 'r',
    url: 'http:/dsadsa.com',
    page: 1,
    data: {
      Name: 'mike',
      Linkedin: 'fsd',
      Title: 'fdsfds',
      'Company Name': 'fdsw',
      'Company Website': 'dsfw',
      'Company Linkedin': 'thre',
      'Company Twitter': 'grev',
      'Company Facebook': 'tgerf',
      Email: 'dfsfew',
      isVerified: true,
      Location: 'cvfgd',
      Employees: '8',
      Phone: '324532',
      Industry: 'fsdgre',
      Keywords: ['fdssf', 'fdse']
    }
  },
  {
    id: '15466',
    scrapeID: 't',
    url: 'http:/dsadsa.com',
    page: 1,
    data: {
      Name: 'mike',
      Linkedin: 'fsd',
      Title: 'fdsfds',
      'Company Name': 'fdsw',
      'Company Website': 'dsfw',
      'Company Linkedin': 'thre',
      'Company Twitter': 'grev',
      'Company Facebook': 'tgerf',
      Email: 'dfsfew',
      isVerified: true,
      Location: 'cvfgd',
      Employees: '8',
      Phone: '324532',
      Industry: 'fsdgre',
      Keywords: ['fdssf', 'fdse']
    }
  },
  {
    id: '75466',
    scrapeID: 't',
    url: 'http:/dsadsa.com',
    page: 1,
    data: {
      Name: 'mike',
      Linkedin: 'fsd',
      Title: 'fdsfds',
      'Company Name': 'fdsw',
      'Company Website': 'dsfw',
      'Company Linkedin': 'thre',
      'Company Twitter': 'grev',
      'Company Facebook': 'tgerf',
      Email: 'dfsfew',
      isVerified: true,
      Location: 'cvfgd',
      Employees: '8',
      Phone: '324532',
      Industry: 'fsdgre',
      Keywords: ['fdssf', 'fdse']
    }
  },
  {
    id: '09876',
    scrapeID: 'y',
    url: 'http:/dsadsa.com',
    page: 1,
    data: {
      Name: 'mike',
      Linkedin: 'fsd',
      Title: 'fdsfds',
      'Company Name': 'fdsw',
      'Company Website': 'dsfw',
      'Company Linkedin': 'thre',
      'Company Twitter': 'grev',
      'Company Facebook': 'tgerf',
      Email: 'dfsfew',
      isVerified: true,
      Location: 'cvfgd',
      Employees: '8',
      Phone: '324532',
      Industry: 'fsdgre',
      Keywords: ['fdssf', 'fdse']
    }
  },
  {
    id: '12eef',
    scrapeID: 'e',
    url: 'http:/dsadsa.com',
    page: 1,
    data: {
      Name: 'mike',
      Linkedin: 'fsd',
      Title: 'fdsfds',
      'Company Name': 'fdsw',
      'Company Website': 'dsfw',
      'Company Linkedin': 'thre',
      'Company Twitter': 'grev',
      'Company Facebook': 'tgerf',
      Email: 'dfsfew',
      isVerified: true,
      Location: 'cvfgd',
      Employees: '8',
      Phone: '324532',
      Industry: 'fsdgre',
      Keywords: ['fdssf', 'fdse']
    }
  },
  {
    id: '5342r',
    scrapeID: 'r',
    url: 'http:/dsadsa.com',
    page: 1,
    data: {
      Name: 'mike',
      Linkedin: 'fsd',
      Title: 'fdsfds',
      'Company Name': 'fdsw',
      'Company Website': 'dsfw',
      'Company Linkedin': 'thre',
      'Company Twitter': 'grev',
      'Company Facebook': 'tgerf',
      Email: 'dfsfew',
      isVerified: true,
      Location: 'cvfgd',
      Employees: '8',
      Phone: '324532',
      Industry: 'fsdgre',
      Keywords: ['fdssf', 'fdse']
    }
  },
  {
    id: '17564',
    scrapeID: 'r',
    url: 'http:/dsadsa.com',
    page: 1,
    data: {
      Name: 'mike',
      Linkedin: 'fsd',
      Title: 'fdsfds',
      'Company Name': 'fdsw',
      'Company Website': 'dsfw',
      'Company Linkedin': 'thre',
      'Company Twitter': 'grev',
      'Company Facebook': 'tgerf',
      Email: 'dfsfew',
      isVerified: true,
      Location: 'cvfgd',
      Employees: '8',
      Phone: '324532',
      Industry: 'fsdgre',
      Keywords: ['fdssf', 'fdse']
    }
  },
  {
    id: '58768',
    scrapeID: 'r',
    url: 'http:/dsadsa.com',
    page: 1,
    data: {
      Name: 'mike',
      Linkedin: 'fsd',
      Title: 'fdsfds',
      'Company Name': 'fdsw',
      'Company Website': 'dsfw',
      'Company Linkedin': 'thre',
      'Company Twitter': 'grev',
      'Company Facebook': 'tgerf',
      Email: 'dfsfew',
      isVerified: true,
      Location: 'cvfgd',
      Employees: '8',
      Phone: '324532',
      Industry: 'fsdgre',
      Keywords: ['fdssf', 'fdse']
    }
  },
  {
    id: '65456',
    scrapeID: 't',
    url: 'http:/dsadsa.com',
    page: 1,
    data: {
      Name: 'mike',
      Linkedin: 'fsd',
      Title: 'fdsfds',
      'Company Name': 'fdsw',
      'Company Website': 'dsfw',
      'Company Linkedin': 'thre',
      'Company Twitter': 'grev',
      'Company Facebook': 'tgerf',
      Email: 'dfsfew',
      isVerified: true,
      Location: 'cvfgd',
      Employees: '8',
      Phone: '324532',
      Industry: 'fsdgre',
      Keywords: ['fdssf', 'fdse']
    }
  },
  {
    id: '987yh',
    scrapeID: 't',
    url: 'http:/dsadsa.com',
    page: 1,
    data: {
      Name: 'mike',
      Linkedin: 'fsd',
      Title: 'fdsfds',
      'Company Name': 'fdsw',
      'Company Website': 'dsfw',
      'Company Linkedin': 'thre',
      'Company Twitter': 'grev',
      'Company Facebook': 'tgerf',
      Email: 'dfsfew',
      isVerified: true,
      Location: 'cvfgd',
      Employees: '8',
      Phone: '324532',
      Industry: 'fsdgre',
      Keywords: ['fdssf', 'fdse']
    }
  },
  {
    id: 'tyr65',
    scrapeID: 'y',
    url: 'http:/dsadsa.com',
    page: 1,
    data: {
      Name: 'mike',
      Linkedin: 'fsd',
      Title: 'fdsfds',
      'Company Name': 'fdsw',
      'Company Website': 'dsfw',
      'Company Linkedin': 'thre',
      'Company Twitter': 'grev',
      'Company Facebook': 'tgerf',
      Email: 'dfsfew',
      isVerified: true,
      Location: 'cvfgd',
      Employees: '8',
      Phone: '324532',
      Industry: 'fsdgre',
      Keywords: ['fdssf', 'fdse']
    }
  }
]
